runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /favicon.ico
  static_files: templates/static/img/logo.png
  upload: templates/static/img/logo.png
  secure: always

- url: /service-worker.js
  static_files: templates/service-worker.js
  upload: templates/service-worker.js
  secure: always

- url: /static
  secure: always
  static_dir: templates/static

- url: /assets
  secure: always
  static_dir: assets

- url: .*
  secure: always
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
